//
// Created by Kasia on 2018-12-28.
//

#ifndef SYMULACJA_SIECI_RECEIVERTYPE_HPP
#define SYMULACJA_SIECI_RECEIVERTYPE_HPP

enum class ReceiverType{
    WORKER, STOREHOUSE,
};
#endif //NETSIM_RECEIVERTYPE_H
